repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: jetstack 
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana 
    url: https://grafana.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: strimzi
    url: https://strimzi.io/charts/

releases:
  # https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm
  # - name: cert-manager
  #   namespace: cert-manager
  #   createNamespace: true
  #   chart: jetstack/cert-manager
  #   version: ^1.3.1
  #   values:
  #     - installCRDs: true


  # https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    createNamespace: true
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: ^4.5.0
    values:
      - ingress:
          enabled: false
          hosts:
            - {{ env "K8S_DASHBOARD_HOST" | default "dashboard.k8s.local" }} 
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: {{ env "SERTIFICATE_ISSUER" | default "letsencrypt-staging" }}
          tls:
            - hosts:
              - {{ env "K8S_DASHBOARD_HOST" | default "dashboard.k8s.local" }} 
              secretName: kubernetes-dashboard-tls
      - metricsScraper: 
          enabled: true
      - metrics-server:
          enabled: true 

  # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
  - name: kube-prometheus-stack
    namespace: monitoring-logs-trace-stack
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: ^17.1.1
    values:
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/alertmanager/values.yaml
      - alertmanager:
          enabled: false
          config:
            receivers:
              - name: default-receiver
                # https://prometheus.io/docs/alerting/latest/configuration/#receiver
          ingress:
            enabled: false
            ingressClassName: nginx
            hosts:
              - {{ env "ALERT_MANAGER_HOST" | default "alertmanager.k8s.local" }}
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: {{ env "SERTIFICATE_ISSUER" | default "letsencrypt-staging" }}
            tls:
              - hosts:
                - {{ env "ALERT_MANAGER_HOST" | default "alertmanager.k8s.local" }}
                secretName: alertmanager-general-tls
      # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
      - grafana:
          enabled: true
          adminPassword: {{ env "GRAFANA_PASSSWORD" | default "prom-operator" }} 
          ingress:
            enabled: false
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: {{ env "SERTIFICATE_ISSUER" | default "letsencrypt-staging" }}
            hosts:
                - {{ env "GRAFANA_HOST" | default "grafana.k8s.local" }}
            tls:
              - hosts:
                - {{ env "GRAFANA_HOST" | default "grafana.k8s.local" }}
                secretName: grafana-general-tls
  
  # https://artifacthub.io/packages/helm/grafana/loki-stack
  - name: loki
    namespace: monitoring-logs-trace-stack
    createNamespace: true
    chart: grafana/loki-stack
    version: ^2.4.1
    values:
      - promtail:
          enabled: true
      - fluent-bit: # can work faster, but plugin for loki not support pod labels
          enabled: false

  # https://artifacthub.io/packages/helm/bitnami/mongodb
  - name: mongodb
    namespace: default
    chart: bitnami/mongodb
    version: ^11.0.3
    values:
      - service.nameOverride: mongo
      - architecture: replicaset
      - auth:
          enabled: true
          rootUser: root
          existingSecret: mongodb-config
      - persistence:
          size: 10G
      # - persistence:
      #     storageClass: civo-volume            

  # https://artifacthub.io/packages/helm/strimzi/strimzi-kafka-operator
  - name: strimzi
    namespace: strimzi
    createNamespace: true
    chart: strimzi/strimzi-kafka-operator
    version: ^0.26.1
    values:
      - watchNamespaces: 
          - default
  
  # https://artifacthub.io/packages/helm/bitnami/redis
  - name: redis
    chart: bitnami/redis
    version: ^16.3.1
    values:
      - auth:
          enabled: true
          sentinel: true
          existingSecret: redis-creds
          existingSecretPasswordKey: REDIS_PASSWORD
      - architecture: replication
      - master:
          service:
            ports:
              redis: 6379
        
          startupProbe:
            enabled: true
          
          resources: 
            requests:
              cpu: "0.3"
              memory: 256M
            limits:
              cpu: "0.5"
              memory: 512M

          persistence:
            enabled: true
            size: 10Gi
      
      - replica:
          replicaCount: 2

          startupProbe:
            enabled: true

          resources: 
            requests:
              cpu: "0.3"
              memory: 256M
            limits:
              cpu: "0.5"
              memory: 512M

          persistence:
            enabled: true
            size: 10Gi

          autoscaling:
            enabled: false

      - sentinel:
          enabled: true
          quorum: 2
          masterSet: mymaster

          service:
            ports:
              sentinel: 26379

          startupProbe:
            enabled: true

          resources: 
            requests:
              cpu: "0.1"
              memory: 128M
            limits:
              cpu: "0.2"
              memory: 128M