apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: cors
metadata:
  name: omnigram-cors
config: 
  origins:
  - https://*.omnigram.ru
  exposed_headers:
  - "*"
  credentials: true
  max_age: 3600
  preflight_continue: false