apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: cors
metadata:
  name: k8s-cors
config: 
  origins:
  - (^|^[^:]+:\/\/|[^\.]+\.)k8s\.local(\:*\d+) # -> actually means *.k8s.local
  - (^|^[^:]+:\/\/|[^\.]+\.)localhost(\:*\d+)
  exposed_headers:
  - "*"
  credentials: true
  max_age: 3600
  preflight_continue: false
